serviceName: service
grpc_write:
  port: :5002
  development: true
grpc_read:
  port: :5001
  development: true
logger:
  level: debug
  devMode: false
  encoder: json
postgres:
  host: localhost
  port: 5431
  user: oem
  password: oem
  dbName: mytest
  sslMode: false
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
