// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cqrs-grpc-test/ent/contact"
	"cqrs-grpc-test/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescCreateTime is the schema descriptor for create_time field.
	contactDescCreateTime := contactFields[3].Descriptor()
	// contact.DefaultCreateTime holds the default value on creation for the create_time field.
	contact.DefaultCreateTime = contactDescCreateTime.Default.(func() time.Time)
	// contactDescUpdateTime is the schema descriptor for update_time field.
	contactDescUpdateTime := contactFields[4].Descriptor()
	// contact.DefaultUpdateTime holds the default value on creation for the update_time field.
	contact.DefaultUpdateTime = contactDescUpdateTime.Default.(func() time.Time)
}
